# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "debian/contrib-stretch64"

  config.vm.define :exchangerateservice do |ci|

  config.vm.synced_folder "../src/main/docker/", "/docker"

    ci.vm.provider "virtualbox" do |vb|
      vb.memory = 4096
      vb.cpus = 2
      # greatly improves network speed. See: https://serverfault.com/questions/495914/vagrant-slow-internet-connection-in-guest
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
      vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
    end

    # exchange-rate-service
    ci.vm.network "forwarded_port", guest: 8080, host: 8080

    ci.vm.provision "docker" do |docker|
      docker.build_image "/docker/postgres",
      args: "-t pcpostgres"
    end

    ci.vm.provision "docker" do |docker|
      docker.run "pcpostgres",
      args: "-p 25432:5432"
    end

    ci.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook-vagrant.yml"
      ansible.verbose = "-vv"
    end

    ci.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yml"
      ansible.extra_vars = {
          spring_active_profile: "vagrant",
          skip_icinga: "yes_please"
      }
      ansible.verbose = "-vv"
    end
  end
end
